### ISSUE TITLE
If cp file doesn't exist, error happens

### ISSUE THREAD

**Issue by edalzell** [Stillat/proteus#10] opened 2021-04-21 23:44 UTC
If one has an addon and the user has NOT published the CP, then when you try to write the CP out, it fails:

```
[2021-04-21 16:41:51] local.ERROR: Could not locate configuration for 'passwordless-login'. {"userId":"cba0aed3-26f9-4ca9-a67f-8261a605d37b","exception":"[object] (Stillat\\Proteus\\Exceptions\\ConfigNotFoundException(code: 0): Could not locate configuration for 'passwordless-login'. at /Users/erin/Sites/simple/vendor/stillat/proteus/src/LaravelConfigWriter.php:341)
[stacktrace]
#0 /Users/erin/Sites/simple/vendor/stillat/proteus/src/LaravelConfigWriter.php(252): Stillat\\Proteus\\LaravelConfigWriter->previewMany('passwordless-lo...', Array)
#1 /Users/erin/Sites/simple/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Stillat\\Proteus\\LaravelConfigWriter->writeMany('passwordless-lo...', Array)
```

Might be nice to create it on the fly?

**Comment by JohnathonKoster** [comment] 2023-02-01 00:50
Going to close this one for now (in 2023 😆)

**Closed as completed by JohnathonKoster** 2023-02-01 00:50 UTC

**Comment by vmitchell85** [comment] 2023-05-24 16:22
+1 on needing this... #flatcamp

**Comment by JohnathonKoster** [comment] 2023-05-24 16:26
@vmitchell85 @edalzell 
I am just not sure what you want the expected behavior to be here? Where should it look to get the original source file (it needs this in order to apply the same formatting, otherwise it will produce weird output)?

Would having a fallback path (that you would need to configure for the addons config directory) be sufficient? If nothing is found, it will fetch from the fallback and effectively publish the file for the user (and at that point is creating files magically for users unexpectedly doing way too much)?

**Comment by vmitchell85** [comment] 2023-05-24 17:01
@JohnathonKoster My use case is pulling in a composer package via my Statamic AddOn and allowing users to override the default configuration using Forma. Since the config doesn't have to be overridden there isn't a config file necessary in the local project unless you are overriding.

I was hoping to allow users to stay in Statamic 100% from the AddOn installation to the configuration without having to publish the config but It seems like I can do that using updater. Also, since v4 tells you to just run the commands for installing AddOns via CLI it's not as necessary.

I also can see how creating files magically for users could be doing too much.

I'll use the updater for now. Thanks for reading & considering my +1.
